//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheConfig) DeepCopyInto(out *CacheConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.RespectOriginCacheControl != nil {
		in, out := &in.RespectOriginCacheControl, &out.RespectOriginCacheControl
		*out = new(bool)
		**out = **in
	}
	if in.StatusHeader != nil {
		in, out := &in.StatusHeader, &out.StatusHeader
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheConfig.
func (in *CacheConfig) DeepCopy() *CacheConfig {
	if in == nil {
		return nil
	}
	out := new(CacheConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptchaConfig) DeepCopyInto(out *CaptchaConfig) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(LocalSecretKeyRef)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]NamedPathRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptchaConfig.
func (in *CaptchaConfig) DeepCopy() *CaptchaConfig {
	if in == nil {
		return nil
	}
	out := new(CaptchaConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CdnTenant) DeepCopyInto(out *CdnTenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CdnTenant.
func (in *CdnTenant) DeepCopy() *CdnTenant {
	if in == nil {
		return nil
	}
	out := new(CdnTenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CdnTenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CdnTenantAutoscalingSpec) DeepCopyInto(out *CdnTenantAutoscalingSpec) {
	*out = *in
	out.ScaleDownStabilization = in.ScaleDownStabilization
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CdnTenantAutoscalingSpec.
func (in *CdnTenantAutoscalingSpec) DeepCopy() *CdnTenantAutoscalingSpec {
	if in == nil {
		return nil
	}
	out := new(CdnTenantAutoscalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CdnTenantAutoscalingStatus) DeepCopyInto(out *CdnTenantAutoscalingStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CdnTenantAutoscalingStatus.
func (in *CdnTenantAutoscalingStatus) DeepCopy() *CdnTenantAutoscalingStatus {
	if in == nil {
		return nil
	}
	out := new(CdnTenantAutoscalingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CdnTenantList) DeepCopyInto(out *CdnTenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CdnTenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CdnTenantList.
func (in *CdnTenantList) DeepCopy() *CdnTenantList {
	if in == nil {
		return nil
	}
	out := new(CdnTenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CdnTenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CdnTenantSpec) DeepCopyInto(out *CdnTenantSpec) {
	*out = *in
	if in.Origins != nil {
		in, out := &in.Origins, &out.Origins
		*out = make([]Origin, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]Domain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Elasticsearch != nil {
		in, out := &in.Elasticsearch, &out.Elasticsearch
		*out = new(ElasticsearchConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(CdnTenantAutoscalingSpec)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CdnTenantSpec.
func (in *CdnTenantSpec) DeepCopy() *CdnTenantSpec {
	if in == nil {
		return nil
	}
	out := new(CdnTenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CdnTenantStatus) DeepCopyInto(out *CdnTenantStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(CdnTenantAutoscalingStatus)
		**out = **in
	}
	if in.DomainTLS != nil {
		in, out := &in.DomainTLS, &out.DomainTLS
		*out = make([]DomainTLSStatus, len(*in))
		copy(*out, *in)
	}
	if in.SecondarySync != nil {
		in, out := &in.SecondarySync, &out.SecondarySync
		*out = make([]SecondarySyncStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CdnTenantStatus.
func (in *CdnTenantStatus) DeepCopy() *CdnTenantStatus {
	if in == nil {
		return nil
	}
	out := new(CdnTenantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Domain) DeepCopyInto(out *Domain) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(DomainTLS)
		(*in).DeepCopyInto(*out)
	}
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = new(CacheConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(SecurityConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Captcha != nil {
		in, out := &in.Captcha, &out.Captcha
		*out = new(CaptchaConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Redirects != nil {
		in, out := &in.Redirects, &out.Redirects
		*out = make([]RedirectRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Domain.
func (in *Domain) DeepCopy() *Domain {
	if in == nil {
		return nil
	}
	out := new(Domain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainTLS) DeepCopyInto(out *DomainTLS) {
	*out = *in
	if in.RedirectHTTPToHTTPS != nil {
		in, out := &in.RedirectHTTPToHTTPS, &out.RedirectHTTPToHTTPS
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainTLS.
func (in *DomainTLS) DeepCopy() *DomainTLS {
	if in == nil {
		return nil
	}
	out := new(DomainTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainTLSStatus) DeepCopyInto(out *DomainTLSStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainTLSStatus.
func (in *DomainTLSStatus) DeepCopy() *DomainTLSStatus {
	if in == nil {
		return nil
	}
	out := new(DomainTLSStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchConfig) DeepCopyInto(out *ElasticsearchConfig) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchConfig.
func (in *ElasticsearchConfig) DeepCopy() *ElasticsearchConfig {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPAccessConfig) DeepCopyInto(out *IPAccessConfig) {
	*out = *in
	if in.AllowCidrs != nil {
		in, out := &in.AllowCidrs, &out.AllowCidrs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BlockCidrs != nil {
		in, out := &in.BlockCidrs, &out.BlockCidrs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPAccessConfig.
func (in *IPAccessConfig) DeepCopy() *IPAccessConfig {
	if in == nil {
		return nil
	}
	out := new(IPAccessConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalSecretKeyRef) DeepCopyInto(out *LocalSecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalSecretKeyRef.
func (in *LocalSecretKeyRef) DeepCopy() *LocalSecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(LocalSecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MethodsConfig) DeepCopyInto(out *MethodsConfig) {
	*out = *in
	if in.Allow != nil {
		in, out := &in.Allow, &out.Allow
		*out = make([]HTTPMethod, len(*in))
		copy(*out, *in)
	}
	if in.Block != nil {
		in, out := &in.Block, &out.Block
		*out = make([]HTTPMethod, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MethodsConfig.
func (in *MethodsConfig) DeepCopy() *MethodsConfig {
	if in == nil {
		return nil
	}
	out := new(MethodsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamedPathRule) DeepCopyInto(out *NamedPathRule) {
	*out = *in
	out.Match = in.Match
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamedPathRule.
func (in *NamedPathRule) DeepCopy() *NamedPathRule {
	if in == nil {
		return nil
	}
	out := new(NamedPathRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Origin) DeepCopyInto(out *Origin) {
	*out = *in
	if in.Weight != nil {
		in, out := &in.Weight, &out.Weight
		*out = new(int32)
		**out = **in
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = new(OriginHealthCheck)
		(*in).DeepCopyInto(*out)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Origin.
func (in *Origin) DeepCopy() *Origin {
	if in == nil {
		return nil
	}
	out := new(Origin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PathMatch) DeepCopyInto(out *PathMatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PathMatch.
func (in *PathMatch) DeepCopy() *PathMatch {
	if in == nil {
		return nil
	}
	out := new(PathMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitConfig) DeepCopyInto(out *RateLimitConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitConfig.
func (in *RateLimitConfig) DeepCopy() *RateLimitConfig {
	if in == nil {
		return nil
	}
	out := new(RateLimitConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedirectPathMatch) DeepCopyInto(out *RedirectPathMatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedirectPathMatch.
func (in *RedirectPathMatch) DeepCopy() *RedirectPathMatch {
	if in == nil {
		return nil
	}
	out := new(RedirectPathMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedirectRule) DeepCopyInto(out *RedirectRule) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	in.When.DeepCopyInto(&out.When)
	if in.PreserveQuery != nil {
		in, out := &in.PreserveQuery, &out.PreserveQuery
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedirectRule.
func (in *RedirectRule) DeepCopy() *RedirectRule {
	if in == nil {
		return nil
	}
	out := new(RedirectRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedirectWhen) DeepCopyInto(out *RedirectWhen) {
	*out = *in
	out.Path = in.Path
	if in.OriginStatus != nil {
		in, out := &in.OriginStatus, &out.OriginStatus
		*out = make([]HTTPStatusCode, len(*in))
		copy(*out, *in)
	}
	if in.UpstreamStatus != nil {
		in, out := &in.UpstreamStatus, &out.UpstreamStatus
		*out = make([]HTTPStatusCode, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedirectWhen.
func (in *RedirectWhen) DeepCopy() *RedirectWhen {
	if in == nil {
		return nil
	}
	out := new(RedirectWhen)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestSecurityConfig) DeepCopyInto(out *RequestSecurityConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestSecurityConfig.
func (in *RequestSecurityConfig) DeepCopy() *RequestSecurityConfig {
	if in == nil {
		return nil
	}
	out := new(RequestSecurityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecondarySyncStatus) DeepCopyInto(out *SecondarySyncStatus) {
	*out = *in
	if in.LastAttemptTime != nil {
		in, out := &in.LastAttemptTime, &out.LastAttemptTime
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessTime != nil {
		in, out := &in.LastSuccessTime, &out.LastSuccessTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecondarySyncStatus.
func (in *SecondarySyncStatus) DeepCopy() *SecondarySyncStatus {
	if in == nil {
		return nil
	}
	out := new(SecondarySyncStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityConfig) DeepCopyInto(out *SecurityConfig) {
	*out = *in
	if in.IPAccess != nil {
		in, out := &in.IPAccess, &out.IPAccess
		*out = new(IPAccessConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Methods != nil {
		in, out := &in.Methods, &out.Methods
		*out = new(MethodsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.URLs != nil {
		in, out := &in.URLs, &out.URLs
		*out = new(URLSecurityConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RateLimit != nil {
		in, out := &in.RateLimit, &out.RateLimit
		*out = new(RateLimitConfig)
		**out = **in
	}
	if in.Request != nil {
		in, out := &in.Request, &out.Request
		*out = new(RequestSecurityConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityConfig.
func (in *SecurityConfig) DeepCopy() *SecurityConfig {
	if in == nil {
		return nil
	}
	out := new(SecurityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *URLSecurityConfig) DeepCopyInto(out *URLSecurityConfig) {
	*out = *in
	if in.Block != nil {
		in, out := &in.Block, &out.Block
		*out = make([]NamedPathRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new URLSecurityConfig.
func (in *URLSecurityConfig) DeepCopy() *URLSecurityConfig {
	if in == nil {
		return nil
	}
	out := new(URLSecurityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OriginHealthCheck) DeepCopyInto(out *OriginHealthCheck) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ExpectedStatus != nil {
		in, out := &in.ExpectedStatus, &out.ExpectedStatus
		*out = new(int32)
		**out = **in
	}
	if in.HealthyThreshold != nil {
		in, out := &in.HealthyThreshold, &out.HealthyThreshold
		*out = new(int32)
		**out = **in
	}
	if in.UnhealthyThreshold != nil {
		in, out := &in.UnhealthyThreshold, &out.UnhealthyThreshold
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OriginHealthCheck.
func (in *OriginHealthCheck) DeepCopy() *OriginHealthCheck {
	if in == nil {
		return nil
	}
	out := new(OriginHealthCheck)
	in.DeepCopyInto(out)
	return out
}
