name: CI DIST
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci-dist.yml
      - dist/**
jobs:
  ci-dist:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: CloudWebManage/cwm-iac/actions/deploy@main
        with:
          commit_message: "Update cwm-cdn-operator/dist"
          content: |
            cwmCdnOperator:
              dist:
                hash: "${{ github.sha }}"
          deploy_key_b64: ${{ secrets.CWM_WORKER_CLUSTER_DEPLOY_KEY_B64 }}
          file_path: config/auto-updated/cwm-cdn-operator/dist.yaml
