name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - dist/**
permissions:
  contents: write
  packages: write
jobs:
  ci:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push
        env:
          IMAGE: ghcr.io/cloudwebmanage/cwm-cdn-operator/operator
          GITHUB_SHA: ${{ github.sha }}
        run: |
          export IMG="${IMAGE}:${GITHUB_SHA}" &&\
          make docker-build docker-push build-installer &&\
          docker tag "$IMG" "${IMAGE}:latest" &&\
          docker push "${IMAGE}:latest" &&\
          if ! git diff --quiet -- dist; then
            git config --global user.name "cwm-cdn-operator" &&\
            git config --global user.email "cwm-cdn-operator@localhost" &&\
            git add dist &&\
            git commit -m "update dist" &&\
            git push origin HEAD:main
          fi
