name: CI
on:
  push:
    paths-ignore:
      - .github/workflows/ci-dist.yml
      - dist/**
permissions:
  contents: write
  packages: write
jobs:
  ci:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Running Tests
        run: |
          go mod tidy
          make test
      - uses: CloudWebManage/cwm-iac/actions/docker-build-push@main
        with:
          image_suffix: cwm-cdn-operator/operator
          deploy_key_b64: ${{ secrets.CWM_WORKER_CLUSTER_DEPLOY_KEY_B64 }}
          deploy_file_path: config/auto-updated/cwm-cdn-operator/operator.yaml
          deploy_content_template: |
            cwmCdnOperator:
              operator:
                image: "__IMAGE__"
          deploy_commit_message: "Update cwm-cdn-operator/operator"
      - name: update dist
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          make build-installer &&\
          if ! git diff --quiet -- dist; then
            git config --global user.name "cwm-cdn-operator" &&\
            git config --global user.email "cwm-cdn-operator@localhost" &&\
            git add dist &&\
            git commit -m "update dist" &&\
            git push origin HEAD:main
          fi
