name: CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push
        env:
          IMG: ghcr.io/cloudwebmanage/cwm-cdn-operator:${GITHUB_SHA}
        run: |
          make docker-build docker-push build-installer
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cwm-cdn-operator-installer
          path: dist
