name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - dist/**
permissions:
  contents: write
  packages: write
jobs:
  ci:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push
        env:
          IMG: ghcr.io/cloudwebmanage/cwm-cdn-operator:${GITHUB_SHA}
        run: |
          make docker-build docker-push build-installer &&\
          git config --global user.name "cwm-cdn-operator" &&\
          git config --global user.email "cwm-cdn-operator@localhost" &&\
          git add dist &&\
          git commit -m "Add dist" &&\
          git push origin HEAD:main
